apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls
  namespace: kubeflow
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "kubeflow.pydemia.org"
  dnsNames:
    - "kubeflow.pydemia.org"
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - "kubeflow.pydemia.org"
  # If you use ‘ingress-gce’, aka the GCLB ingress controller
  # acme:
  #   config:
  #   - http01:
  #       ingress: name-of-gce-ingress-resource
  #     domains:
  #     - example.com
  #     - www.example.com