# apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
# apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  # namespace: kubeflow
spec:
  acme:
    email: pydemia@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      # `kubectl -n cert-manager get secrets letsencrypt-staging-private-key`
      name: letsencrypt-staging-private-key
    # http01: {}
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
---
# apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
# apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # namespace: kubeflow
spec:
  acme:
    email: pydemia@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      # `kubectl -n cert-manager get secrets letsencrypt-staging-private-key`
      name: letsencrypt-prod-private-key
  solvers:
  # An empty 'selector' means that this solver matches all domains
  - selector: {}
    http01:
       ingress:
         class:  nginx
# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Certificate
# metadata:
#   name: nginx-tls
#   namespace: kubeflow
# spec:
#   secretName: nginx-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: kubeflow.pydemia.org
#   dnsNames:
#     - kubeflow.pydemia.org
#   acme:
#     config:
#       - http01:
#         ingressClass: nginx
#         domains:
#           - kubeflow.pydemia.org